#!/bin/bash

download_link="https://github.com/JulenRa-dev/DebsLang/raw/main/DebsLang_Linux.tar.gz"
echo "Downloading DebsLang..."

curl $download_link > to_download.tar.gz

echo "Decompressing DebsLang..."

tar -xvzf to_download.tar.gz

echo "Installation completed."
echo "Please check for any errors above."
read -p "Press enter to close..."